version: "3"

services:
  qemu:
    container_name: qemu
    image: qemux/qemu-docker:latest
    environment:
      DISPLAY: "vnc"
      BOOT: "https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/x86_64/alpine-virt-3.19.0-x86_64.iso"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 2222:22
      - 5900:5900
    stop_grace_period: 2m
    restart: unless-stopped
      
  web-server:
    image: httpd:latest
    # ports:
    #   - "80:80"
    volumes:
      - ./scripts/:/scripts/
    networks:
      - internal_network

  probe_machine:
    image: alpine:latest
    networks:
      - internal_network
    command: ["tail", "-f", "/dev/null"]

networks:
  internal_network:
    driver: bridge
    # driver: 'service:firewall'
